# Generated by Django 4.2.4 on 2023-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_AgroYdrata', '0002_dados_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='tp_planta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='dados',
            table='dados',
        ),
    ]
