# Generated by Django 4.2.4 on 2023-09-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_AgroYdrata', '0003_alter_dados_tp_planta_alter_dados_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dados',
            table=None,
        ),
    ]
