# Generated by Django 4.2.4 on 2023-09-16 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_AgroYdrata', '0004_alter_dados_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_insercao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dados',
            name='horario_insercao',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
